// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace business.person
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class User : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""User"",""namespace"":""business.person"",""fields"":[{""name"":""id"",""doc"":""Идентфикатор пользователя"",""type"":""int""},{""name"":""name"",""doc"":""Имя пользователя"",""type"":""string""},{""name"":""gender"",""doc"":""Gender of User"",""type"":{""type"":""enum"",""name"":""Gender"",""namespace"":""business.person"",""symbols"":[""Man"",""Woman""]}}]}");
		/// <summary>
		/// Идентфикатор пользователя
		/// </summary>
		private int _id;
		/// <summary>
		/// Имя пользователя
		/// </summary>
		private string _name;
		/// <summary>
		/// Gender of User
		/// </summary>
		private business.person.Gender _gender;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return User._SCHEMA;
			}
		}
		/// <summary>
		/// Идентфикатор пользователя
		/// </summary>
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// Имя пользователя
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		/// <summary>
		/// Gender of User
		/// </summary>
		public business.person.Gender gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				this._gender = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.name;
			case 2: return this.gender;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.gender = (business.person.Gender)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
